title: Researcher
url: "https://lelivre.github.io"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/lelivre"
footer_text: "For a great mind, nothing is little"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "home"
 - name: "About"
   link: "aboutme"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Frontier"
   link: "frontier"
 - name: "Contact"
   link: "contact"

#remote_theme: ankitsultana/researcher@gem
