title: Researcher
url: "https://lelivre.github.io"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/lelivre"
footer_text: "Human greatness does not lie in wealth or power, but in character and goodness. --Anne Frank"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "home"
# - name: "About"
#   link: "aboutme"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Links"
   link: "links"
 - name: "Contact"
   link: "contact"

#remote_theme: ankitsultana/researcher@gem
